<?php
/**
 * Created by PhpStorm.
 * User: N_Juraev
 * Date: 01.03.2016
 * Time: 11:55
 */
namespace app\models;



class ProgrammistsSearch extends Programmists
{

    public function rules()
    {
        return [
            [['Surname', 'Name', 'Patronymic','Login','Email',], 'safe']
        ]; // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }

    public function search($params)
    {
        $query = Programmists::find();
        $query->joinWith('operator');
        $dataProvider = new \yii\data\ActiveDataProvider([
            'query' => $query,
            'sort' => [
                'defaultOrder' => ['id' => SORT_ASC]
            ]
        ]);
        if (!$this->load($params) && $this->validate()) {
            return $dataProvider;
        }

        $this->addConditions($query, 'Surname', true);
        $this->addConditions($query, 'Name', true);
        $this->addConditions($query, 'Patronymic', true);
        $this->addConditions($query, 'Operator', true);
        $this->addConditions($query, 'Tel', true);
        $this->addConditions($query, 'Email', true);
        $this->addConditions($query, 'Login', true);
        return $dataProvider;

    }

    protected function addConditions($query, $attribute, $partialMatch = false)
    {
        if (($pos = strrpos($attribute, '.')) !== false) {
            $modelAttribute = substr($attribute, $pos + 1);
        } else {
            $modelAttribute = $attribute;
        }

        $value = $this->$modelAttribute;
        if (trim($value) === '') {
            return;
        }

        /*
         * The following line is additionally added for right aliasing
         * of columns so filtering happen correctly in the self join
         */
        $attribute = "programmists." . $attribute;

        if ($partialMatch) {
            $query->andWhere(['like', $attribute, $value]);
        } else {
            $query->andWhere([$attribute => $value]);

        }

    }
}