<?php
/**
 * Created by PhpStorm.
 * User: N_Juraev
 * Date: 18.03.2016
 * Time: 10:59
 */
namespace app\models;

class SprPurveyorsSearch extends SprPurveyors{

    function rules()
    {
        return [
            [['Purveyor','Site','Surname','Name','Patronymic','Tel'],'safe']
        ]; // TODO: Change the autogenerated stub
    }

    function search($params){
        $query = SprPurveyors::find();
        $query->joinWith('operator');
        $dataProvider = new \yii\data\ActiveDataProvider([
            'query' => $query,
            'sort' => [
                'defaultOrder' => ['id' => SORT_ASC]
            ]
        ]);
        if (!$this->load($params) && $this->validate()) {
            return $dataProvider;
        }

        $this->addConditions($query, 'Purveyor', true);
        $this->addConditions($query, 'Site', true);
        $this->addConditions($query, 'Surname', true);
        $this->addConditions($query, 'Name', true);
        $this->addConditions($query, 'Patronymic', true);

        $this->addConditions($query, 'Tel', true);
        return $dataProvider;
    }

    protected function addConditions($query, $attribute, $partialMatch = false)
    {
        if (($pos = strrpos($attribute, '.')) !== false) {
            $modelAttribute = substr($attribute, $pos + 1);
        } else {
            $modelAttribute = $attribute;
        }

        $value = $this->$modelAttribute;
        if (trim($value) === '') {
            return;
        }

        /*
         * The following line is additionally added for right aliasing
         * of columns so filtering happen correctly in the self join
         */
        $attribute = "spr_purveyors." . $attribute;

        if ($partialMatch) {
            $query->andWhere(['like', $attribute, $value]);
        } else {
            $query->andWhere([$attribute => $value]);

        }

    }
}