<?php
/**
 * Created by PhpStorm.
 * User: N_Juraev
 * Date: 07.03.2016
 * Time: 14:39
 */
namespace app\models;

use Yii;

class SprScriptStatusSearch extends SprScriptStatus{
    function rules()
    {
        return [
            [['ScriptStatus','StatusId'],'safe']
        ]; // TODO: Change the autogenerated stub
    }

    public function search($params)
    {
        $query = SprScriptStatus::find();

        $dataProvider = new \yii\data\ActiveDataProvider([
            'query' => $query,
            'sort' => [
                'defaultOrder' => ['id' => SORT_ASC]
            ]
        ]);
        if (!$this->load($params) && $this->validate()) {
            return $dataProvider;
        }
        $this->addConditions($query, 'ScriptStatus', true);
        $this->addConditions($query, 'StatusId', true);
        return $dataProvider;

    }

    protected function addConditions($query, $attribute, $partialMatch = false)
    {
        if (($pos = strrpos($attribute, '.')) !== false) {
            $modelAttribute = substr($attribute, $pos + 1);
        } else {
            $modelAttribute = $attribute;
        }

        $value = $this->$modelAttribute;
        if (trim($value) === '') {
            return;
        }

        /*
         * The following line is additionally added for right aliasing
         * of columns so filtering happen correctly in the self join
         */
        $attribute = "spr_script_status." . $attribute;

        if ($partialMatch) {
            $query->andWhere(['like', $attribute, $value]);
        } else {
            $query->andWhere([$attribute => $value]);

        }

    }
}